name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
    - name: npm install, test JS standard and  build test app
      run: |
        npm install
        npm run lint --if-present
        npm run build
      env:
        CI: true
    - name: Test Code
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
      with:
        args: npm test
